# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  serialized_pb=_b('\n\rmessage.proto\"e\n\x07\x43ityAoi\x12&\n\x06player\x18\x01 \x03(\x0b\x32\x16.CityAoi.PlayerCityAoi\x1a\x32\n\rPlayerCityAoi\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x10\n\x08target_x\x18\x02 \x01(\x05\"!\n\x08\x43ityAois\x12\x15\n\x03\x43\x41S\x18\x01 \x03(\x0b\x32\x08.CityAoi')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CITYAOI_PLAYERCITYAOI = _descriptor.Descriptor(
  name='PlayerCityAoi',
  full_name='CityAoi.PlayerCityAoi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='CityAoi.PlayerCityAoi.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_x', full_name='CityAoi.PlayerCityAoi.target_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=118,
)

_CITYAOI = _descriptor.Descriptor(
  name='CityAoi',
  full_name='CityAoi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='CityAoi.player', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CITYAOI_PLAYERCITYAOI, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=118,
)


_CITYAOIS = _descriptor.Descriptor(
  name='CityAois',
  full_name='CityAois',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CAS', full_name='CityAois.CAS', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=153,
)

_CITYAOI_PLAYERCITYAOI.containing_type = _CITYAOI
_CITYAOI.fields_by_name['player'].message_type = _CITYAOI_PLAYERCITYAOI
_CITYAOIS.fields_by_name['CAS'].message_type = _CITYAOI
DESCRIPTOR.message_types_by_name['CityAoi'] = _CITYAOI
DESCRIPTOR.message_types_by_name['CityAois'] = _CITYAOIS

CityAoi = _reflection.GeneratedProtocolMessageType('CityAoi', (_message.Message,), dict(

  PlayerCityAoi = _reflection.GeneratedProtocolMessageType('PlayerCityAoi', (_message.Message,), dict(
    DESCRIPTOR = _CITYAOI_PLAYERCITYAOI,
    __module__ = 'message_pb2'
    # @@protoc_insertion_point(class_scope:CityAoi.PlayerCityAoi)
    ))
  ,
  DESCRIPTOR = _CITYAOI,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:CityAoi)
  ))
_sym_db.RegisterMessage(CityAoi)
_sym_db.RegisterMessage(CityAoi.PlayerCityAoi)

CityAois = _reflection.GeneratedProtocolMessageType('CityAois', (_message.Message,), dict(
  DESCRIPTOR = _CITYAOIS,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:CityAois)
  ))
_sym_db.RegisterMessage(CityAois)


# @@protoc_insertion_point(module_scope)
